// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  BattleState,
} from "./types";


export default __t.row({
  playerIdentity: __t.identity().primaryKey().name("player_identity"),
  get state() {
    return BattleState;
  },
  enemyLevel: __t.u8().name("enemy_level"),
  lastPlayerSkillId: __t.u32().name("last_player_skill_id"),
  lastEnemySkillId: __t.u32().name("last_enemy_skill_id"),
});
