// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  Direction,
  ActionState,
  MoveInput,
} from "./types";


export default __t.row({
  entityId: __t.u64().primaryKey().name("entity_id"),
  mapId: __t.u32().name("map_id"),
  tileX: __t.i32().name("tile_x"),
  tileY: __t.i32().name("tile_y"),
  get facing() {
    return Direction;
  },
  get action() {
    return ActionState;
  },
  moveStartedAtMs: __t.i64().name("move_started_at_ms"),
  spriteId: __t.u32().name("sprite_id"),
  get moveQueue() {
    return __t.array(MoveInput).name("move_queue");
  },
});
