// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.6.0 (commit 31fd1c8c3346dfec38dfcc2e89c2ecf457cf26ff).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import AcceptChallengeReducer from "./accept_challenge_reducer";
import AttemptRecruitReducer from "./attempt_recruit_reducer";
import CancelTradeReducer from "./cancel_trade_reducer";
import CareForMonsterReducer from "./care_for_monster_reducer";
import ChallengePlayerReducer from "./challenge_player_reducer";
import ClearQueueReducer from "./clear_queue_reducer";
import CloseBattleReducer from "./close_battle_reducer";
import ConfirmTradeReducer from "./confirm_trade_reducer";
import DeclineChallengeReducer from "./decline_challenge_reducer";
import EnqueueMoveReducer from "./enqueue_move_reducer";
import EvolveMonsterReducer from "./evolve_monster_reducer";
import FuseMonstersReducer from "./fuse_monsters_reducer";
import HealPartyReducer from "./heal_party_reducer";
import InviteToRaidReducer from "./invite_to_raid_reducer";
import JoinGameReducer from "./join_game_reducer";
import OfferTradeReducer from "./offer_trade_reducer";
import RenameMonsterReducer from "./rename_monster_reducer";
import RespondTradeReducer from "./respond_trade_reducer";
import SetMoveReducer from "./set_move_reducer";
import SetPartySlotReducer from "./set_party_slot_reducer";
import StartBattleReducer from "./start_battle_reducer";
import SubmitActionReducer from "./submit_action_reducer";
import SwapActiveReducer from "./swap_active_reducer";
import TrainMonsterReducer from "./train_monster_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import BattleRow from "./battle_table";
import BattleActionRow from "./battle_action_table";
import BattleChallengeRow from "./battle_challenge_table";
import CharacterRow from "./character_table";
import ConfigRow from "./config_table";
import FusionRow from "./fusion_table";
import ItemRow from "./item_table";
import MonsterRow from "./monster_table";
import NpcRow from "./npc_table";
import PlayerRow from "./player_table";
import PlayerItemRow from "./player_item_table";
import ProfileRow from "./profile_table";
import SkillRow from "./skill_table";
import SpeciesRow from "./species_table";
import TradeOfferRow from "./trade_offer_table";
import TypeRelationRow from "./type_relation_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  battle: __table({
    name: 'battle',
    indexes: [
      { accessor: 'battle_id', name: 'battle_battle_id_idx_btree', algorithm: 'btree', columns: [
        'battleId',
      ] },
      { accessor: 'opponent_identity', name: 'battle_opponent_identity_idx_btree', algorithm: 'btree', columns: [
        'opponentIdentity',
      ] },
      { accessor: 'player_identity', name: 'battle_player_identity_idx_btree', algorithm: 'btree', columns: [
        'playerIdentity',
      ] },
    ],
    constraints: [
      { name: 'battle_battle_id_key', constraint: 'unique', columns: ['battleId'] },
    ],
  }, BattleRow),
  battle_action: __table({
    name: 'battle_action',
    indexes: [
      { accessor: 'battle_id', name: 'battle_action_battle_id_idx_btree', algorithm: 'btree', columns: [
        'battleId',
      ] },
      { accessor: 'id', name: 'battle_action_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'battle_action_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, BattleActionRow),
  battle_challenge: __table({
    name: 'battle_challenge',
    indexes: [
      { accessor: 'from_identity', name: 'battle_challenge_from_identity_idx_btree', algorithm: 'btree', columns: [
        'fromIdentity',
      ] },
      { accessor: 'id', name: 'battle_challenge_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'to_identity', name: 'battle_challenge_to_identity_idx_btree', algorithm: 'btree', columns: [
        'toIdentity',
      ] },
    ],
    constraints: [
      { name: 'battle_challenge_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, BattleChallengeRow),
  character: __table({
    name: 'character',
    indexes: [
      { accessor: 'entity_id', name: 'character_entity_id_idx_btree', algorithm: 'btree', columns: [
        'entityId',
      ] },
    ],
    constraints: [
      { name: 'character_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, CharacterRow),
  config: __table({
    name: 'config',
    indexes: [
      { accessor: 'id', name: 'config_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'config_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ConfigRow),
  fusion: __table({
    name: 'fusion',
    indexes: [
      { accessor: 'id', name: 'fusion_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'fusion_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, FusionRow),
  item: __table({
    name: 'item',
    indexes: [
      { accessor: 'item_id', name: 'item_item_id_idx_btree', algorithm: 'btree', columns: [
        'itemId',
      ] },
    ],
    constraints: [
      { name: 'item_item_id_key', constraint: 'unique', columns: ['itemId'] },
    ],
  }, ItemRow),
  monster: __table({
    name: 'monster',
    indexes: [
      { accessor: 'monster_id', name: 'monster_monster_id_idx_btree', algorithm: 'btree', columns: [
        'monsterId',
      ] },
      { accessor: 'owner_identity', name: 'monster_owner_identity_idx_btree', algorithm: 'btree', columns: [
        'ownerIdentity',
      ] },
    ],
    constraints: [
      { name: 'monster_monster_id_key', constraint: 'unique', columns: ['monsterId'] },
    ],
  }, MonsterRow),
  npc: __table({
    name: 'npc',
    indexes: [
      { accessor: 'entity_id', name: 'npc_entity_id_idx_btree', algorithm: 'btree', columns: [
        'entityId',
      ] },
    ],
    constraints: [
      { name: 'npc_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, NpcRow),
  player: __table({
    name: 'player',
    indexes: [
      { accessor: 'entity_id', name: 'player_entity_id_idx_btree', algorithm: 'btree', columns: [
        'entityId',
      ] },
      { accessor: 'identity', name: 'player_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'player_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, PlayerRow),
  player_item: __table({
    name: 'player_item',
    indexes: [
      { accessor: 'id', name: 'player_item_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'owner_identity', name: 'player_item_owner_identity_idx_btree', algorithm: 'btree', columns: [
        'ownerIdentity',
      ] },
    ],
    constraints: [
      { name: 'player_item_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PlayerItemRow),
  profile: __table({
    name: 'profile',
    indexes: [
      { accessor: 'identity', name: 'profile_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'profile_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, ProfileRow),
  skill: __table({
    name: 'skill',
    indexes: [
      { accessor: 'skill_id', name: 'skill_skill_id_idx_btree', algorithm: 'btree', columns: [
        'skillId',
      ] },
    ],
    constraints: [
      { name: 'skill_skill_id_key', constraint: 'unique', columns: ['skillId'] },
    ],
  }, SkillRow),
  species: __table({
    name: 'species',
    indexes: [
      { accessor: 'species_id', name: 'species_species_id_idx_btree', algorithm: 'btree', columns: [
        'speciesId',
      ] },
    ],
    constraints: [
      { name: 'species_species_id_key', constraint: 'unique', columns: ['speciesId'] },
    ],
  }, SpeciesRow),
  trade_offer: __table({
    name: 'trade_offer',
    indexes: [
      { accessor: 'from_identity', name: 'trade_offer_from_identity_idx_btree', algorithm: 'btree', columns: [
        'fromIdentity',
      ] },
      { accessor: 'id', name: 'trade_offer_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'to_identity', name: 'trade_offer_to_identity_idx_btree', algorithm: 'btree', columns: [
        'toIdentity',
      ] },
    ],
    constraints: [
      { name: 'trade_offer_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, TradeOfferRow),
  type_relation: __table({
    name: 'type_relation',
    indexes: [
      { accessor: 'id', name: 'type_relation_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'type_relation_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, TypeRelationRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("accept_challenge", AcceptChallengeReducer),
  __reducerSchema("attempt_recruit", AttemptRecruitReducer),
  __reducerSchema("cancel_trade", CancelTradeReducer),
  __reducerSchema("care_for_monster", CareForMonsterReducer),
  __reducerSchema("challenge_player", ChallengePlayerReducer),
  __reducerSchema("clear_queue", ClearQueueReducer),
  __reducerSchema("close_battle", CloseBattleReducer),
  __reducerSchema("confirm_trade", ConfirmTradeReducer),
  __reducerSchema("decline_challenge", DeclineChallengeReducer),
  __reducerSchema("enqueue_move", EnqueueMoveReducer),
  __reducerSchema("evolve_monster", EvolveMonsterReducer),
  __reducerSchema("fuse_monsters", FuseMonstersReducer),
  __reducerSchema("heal_party", HealPartyReducer),
  __reducerSchema("invite_to_raid", InviteToRaidReducer),
  __reducerSchema("join_game", JoinGameReducer),
  __reducerSchema("offer_trade", OfferTradeReducer),
  __reducerSchema("rename_monster", RenameMonsterReducer),
  __reducerSchema("respond_trade", RespondTradeReducer),
  __reducerSchema("set_move", SetMoveReducer),
  __reducerSchema("set_party_slot", SetPartySlotReducer),
  __reducerSchema("start_battle", StartBattleReducer),
  __reducerSchema("submit_action", SubmitActionReducer),
  __reducerSchema("swap_active", SwapActiveReducer),
  __reducerSchema("train_monster", TrainMonsterReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.6.0" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The procedures available in this remote SpacetimeDB module. */
export const procedures = __convertToAccessorMap(proceduresSchema.procedures);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

