// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  Potential,
  Temperament,
  Training,
  StatBlock,
} from "./types";


export default __t.row({
  monsterId: __t.u64().primaryKey().name("monster_id"),
  ownerIdentity: __t.identity().name("owner_identity"),
  speciesId: __t.u32().name("species_id"),
  nickname: __t.string(),
  level: __t.u8(),
  xp: __t.u32(),
  xpFloor: __t.u32().name("xp_floor"),
  xpNext: __t.u32().name("xp_next"),
  get potential() {
    return Potential;
  },
  get temperament() {
    return Temperament;
  },
  get training() {
    return Training;
  },
  bond: __t.u16(),
  currentHp: __t.u16().name("current_hp"),
  get derived() {
    return StatBlock;
  },
  partySlot: __t.option(__t.u8()).name("party_slot"),
  lastCareAtMs: __t.i64().name("last_care_at_ms"),
  evolvesTo: __t.array(__t.u32()).name("evolves_to"),
});
