// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  entityId: __t.u64().primaryKey().name("entity_id"),
  homeX: __t.i32().name("home_x"),
  homeY: __t.i32().name("home_y"),
  wanderRadius: __t.i32().name("wander_radius"),
  nextMoveAtMs: __t.i64().name("next_move_at_ms"),
});
