// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  Affinity,
  Category,
} from "./types";


export default __t.row({
  skillId: __t.u32().primaryKey().name("skill_id"),
  name: __t.string(),
  get affinity() {
    return Affinity;
  },
  get category() {
    return Category;
  },
  power: __t.u16(),
});
