// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  Affinity,
  StatBlock,
  Evolution,
} from "./types";


export default __t.row({
  speciesId: __t.u32().primaryKey().name("species_id"),
  name: __t.string(),
  get base() {
    return StatBlock;
  },
  get primaryAffinity() {
    return Affinity.name("primary_affinity");
  },
  get secondaryAffinity() {
    return __t.option(Affinity).name("secondary_affinity");
  },
  spriteId: __t.u32().name("sprite_id"),
  skills: __t.array(__t.u32()),
  recruitRate: __t.u16().name("recruit_rate"),
  get evolutions() {
    return __t.array(Evolution);
  },
});
