// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  MonsterCard,
  TradeStatus,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  fromIdentity: __t.identity().name("from_identity"),
  toIdentity: __t.identity().name("to_identity"),
  get fromCard() {
    return MonsterCard.name("from_card");
  },
  get toCard() {
    return __t.option(MonsterCard).name("to_card");
  },
  get status() {
    return TradeStatus;
  },
  createdAtMs: __t.i64().name("created_at_ms"),
});
