// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

// The tagged union or sum type for the algebraic type `ActionState`.
export const ActionState = __t.enum("ActionState", {
  Idle: __t.unit(),
  Walking: __t.unit(),
  Jumping: __t.unit(),
});
export type ActionState = __Infer<typeof ActionState>;

// The tagged union or sum type for the algebraic type `Affinity`.
export const Affinity = __t.enum("Affinity", {
  Neutral: __t.unit(),
  Fire: __t.unit(),
  Water: __t.unit(),
  Nature: __t.unit(),
  Electric: __t.unit(),
  Earth: __t.unit(),
  Light: __t.unit(),
  Dark: __t.unit(),
});
export type Affinity = __Infer<typeof Affinity>;

export const AttackEvent = __t.object("AttackEvent", {
  byPlayer: __t.bool(),
  skillId: __t.u32(),
  damage: __t.u16(),
  get effectiveness() {
    return Effectiveness;
  },
});
export type AttackEvent = __Infer<typeof AttackEvent>;

export const Battle = __t.object("Battle", {
  battleId: __t.u64(),
  playerIdentity: __t.identity(),
  opponentIdentity: __t.identity(),
  get state() {
    return BattleState;
  },
  enemyLevel: __t.u8(),
  partyMonsterIds: __t.array(__t.u64()),
  opponentMonsterIds: __t.array(__t.u64()),
  get wildPotential() {
    return Potential;
  },
  get wildTemperament() {
    return Temperament;
  },
  get lastEvents() {
    return __t.array(BattleEvent);
  },
  lastXpGain: __t.u32(),
  leveledUp: __t.bool(),
});
export type Battle = __Infer<typeof Battle>;

export const BattleAction = __t.object("BattleAction", {
  id: __t.u64(),
  battleId: __t.u64(),
  chooserIdentity: __t.identity(),
  skillId: __t.u32(),
});
export type BattleAction = __Infer<typeof BattleAction>;

export const BattleChallenge = __t.object("BattleChallenge", {
  id: __t.u64(),
  fromIdentity: __t.identity(),
  toIdentity: __t.identity(),
  createdAtMs: __t.i64(),
});
export type BattleChallenge = __Infer<typeof BattleChallenge>;

// The tagged union or sum type for the algebraic type `BattleEvent`.
export const BattleEvent = __t.enum("BattleEvent", {
  get Attack() {
    return AttackEvent;
  },
  get Fainted() {
    return FaintEvent;
  },
  get Switched() {
    return SwitchEvent;
  },
  RecruitFailed: __t.unit(),
});
export type BattleEvent = __Infer<typeof BattleEvent>;

export const BattleMonster = __t.object("BattleMonster", {
  speciesId: __t.u32(),
  level: __t.u8(),
  get affinity() {
    return Affinity;
  },
  attack: __t.u16(),
  defense: __t.u16(),
  special: __t.u16(),
  speed: __t.u16(),
  maxHp: __t.u16(),
  currentHp: __t.u16(),
});
export type BattleMonster = __Infer<typeof BattleMonster>;

// The tagged union or sum type for the algebraic type `BattleOutcome`.
export const BattleOutcome = __t.enum("BattleOutcome", {
  Ongoing: __t.unit(),
  PlayerWon: __t.unit(),
  PlayerLost: __t.unit(),
  Recruited: __t.unit(),
});
export type BattleOutcome = __Infer<typeof BattleOutcome>;

export const BattleSide = __t.object("BattleSide", {
  get team() {
    return __t.array(BattleMonster);
  },
  active: __t.u8(),
});
export type BattleSide = __Infer<typeof BattleSide>;

export const BattleState = __t.object("BattleState", {
  get player() {
    return BattleSide;
  },
  get enemy() {
    return BattleSide;
  },
  get outcome() {
    return BattleOutcome;
  },
  turn: __t.u32(),
});
export type BattleState = __Infer<typeof BattleState>;

// The tagged union or sum type for the algebraic type `Category`.
export const Category = __t.enum("Category", {
  Physical: __t.unit(),
  Special: __t.unit(),
});
export type Category = __Infer<typeof Category>;

export const Character = __t.object("Character", {
  entityId: __t.u64(),
  mapId: __t.u32(),
  tileX: __t.i32(),
  tileY: __t.i32(),
  get facing() {
    return Direction;
  },
  get action() {
    return ActionState;
  },
  moveStartedAtMs: __t.i64(),
  spriteId: __t.u32(),
  get moveQueue() {
    return __t.array(MoveInput);
  },
});
export type Character = __Infer<typeof Character>;

export const Config = __t.object("Config", {
  id: __t.u32(),
  mapId: __t.u32(),
});
export type Config = __Infer<typeof Config>;

// The tagged union or sum type for the algebraic type `Direction`.
export const Direction = __t.enum("Direction", {
  North: __t.unit(),
  South: __t.unit(),
  East: __t.unit(),
  West: __t.unit(),
});
export type Direction = __Infer<typeof Direction>;

// The tagged union or sum type for the algebraic type `Effectiveness`.
export const Effectiveness = __t.enum("Effectiveness", {
  NoEffect: __t.unit(),
  NotVeryEffective: __t.unit(),
  Neutral: __t.unit(),
  SuperEffective: __t.unit(),
});
export type Effectiveness = __Infer<typeof Effectiveness>;

export const Encounter = __t.object("Encounter", {
  id: __t.u64(),
  zoneId: __t.u32(),
  speciesId: __t.u32(),
  weight: __t.u32(),
  minLevel: __t.u8(),
  maxLevel: __t.u8(),
});
export type Encounter = __Infer<typeof Encounter>;

export const Evolution = __t.object("Evolution", {
  to: __t.u32(),
  minLevel: __t.u8(),
  minBond: __t.u16(),
});
export type Evolution = __Infer<typeof Evolution>;

export const FaintEvent = __t.object("FaintEvent", {
  playerSide: __t.bool(),
  speciesId: __t.u32(),
});
export type FaintEvent = __Infer<typeof FaintEvent>;

export const Fusion = __t.object("Fusion", {
  id: __t.u64(),
  a: __t.u32(),
  b: __t.u32(),
  to: __t.u32(),
});
export type Fusion = __Infer<typeof Fusion>;

export const Item = __t.object("Item", {
  itemId: __t.u32(),
  name: __t.string(),
  recruitBonus: __t.u16(),
  get trainStat() {
    return __t.option(Stat);
  },
  trainAmount: __t.u16(),
});
export type Item = __Infer<typeof Item>;

export const Monster = __t.object("Monster", {
  monsterId: __t.u64(),
  ownerIdentity: __t.identity(),
  speciesId: __t.u32(),
  nickname: __t.string(),
  level: __t.u8(),
  xp: __t.u32(),
  xpFloor: __t.u32(),
  xpNext: __t.u32(),
  get potential() {
    return Potential;
  },
  get temperament() {
    return Temperament;
  },
  get training() {
    return Training;
  },
  bond: __t.u16(),
  currentHp: __t.u16(),
  get derived() {
    return StatBlock;
  },
  partySlot: __t.option(__t.u8()),
  lastCareAtMs: __t.i64(),
  evolvesTo: __t.array(__t.u32()),
});
export type Monster = __Infer<typeof Monster>;

export const MonsterCard = __t.object("MonsterCard", {
  monsterId: __t.u64(),
  speciesId: __t.u32(),
  nickname: __t.string(),
  level: __t.u8(),
  get derived() {
    return StatBlock;
  },
  get potential() {
    return Potential;
  },
  get temperament() {
    return Temperament;
  },
  bond: __t.u16(),
});
export type MonsterCard = __Infer<typeof MonsterCard>;

// The tagged union or sum type for the algebraic type `MoveInput`.
export const MoveInput = __t.enum("MoveInput", {
  get Step() {
    return Direction;
  },
  Jump: __t.unit(),
});
export type MoveInput = __Infer<typeof MoveInput>;

export const MovementTickSchedule = __t.object("MovementTickSchedule", {
  id: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type MovementTickSchedule = __Infer<typeof MovementTickSchedule>;

export const Npc = __t.object("Npc", {
  entityId: __t.u64(),
  homeX: __t.i32(),
  homeY: __t.i32(),
  wanderRadius: __t.i32(),
  nextMoveAtMs: __t.i64(),
});
export type Npc = __Infer<typeof Npc>;

export const Player = __t.object("Player", {
  identity: __t.identity(),
  entityId: __t.u64(),
  name: __t.string(),
  online: __t.bool(),
  lastInputSeq: __t.u64(),
});
export type Player = __Infer<typeof Player>;

export const PlayerItem = __t.object("PlayerItem", {
  id: __t.u64(),
  ownerIdentity: __t.identity(),
  itemId: __t.u32(),
  quantity: __t.u32(),
});
export type PlayerItem = __Infer<typeof PlayerItem>;

export const Potential = __t.object("Potential", {
  hp: __t.u8(),
  attack: __t.u8(),
  defense: __t.u8(),
  special: __t.u8(),
  speed: __t.u8(),
});
export type Potential = __Infer<typeof Potential>;

export const Profile = __t.object("Profile", {
  identity: __t.identity(),
  name: __t.string(),
  rating: __t.i32(),
  wins: __t.u32(),
  losses: __t.u32(),
});
export type Profile = __Infer<typeof Profile>;

export const Skill = __t.object("Skill", {
  skillId: __t.u32(),
  name: __t.string(),
  get affinity() {
    return Affinity;
  },
  get category() {
    return Category;
  },
  power: __t.u16(),
});
export type Skill = __Infer<typeof Skill>;

export const Species = __t.object("Species", {
  speciesId: __t.u32(),
  name: __t.string(),
  get base() {
    return StatBlock;
  },
  get primaryAffinity() {
    return Affinity;
  },
  get secondaryAffinity() {
    return __t.option(Affinity);
  },
  spriteId: __t.u32(),
  skills: __t.array(__t.u32()),
  recruitRate: __t.u16(),
  get evolutions() {
    return __t.array(Evolution);
  },
});
export type Species = __Infer<typeof Species>;

// The tagged union or sum type for the algebraic type `Stat`.
export const Stat = __t.enum("Stat", {
  Hp: __t.unit(),
  Attack: __t.unit(),
  Defense: __t.unit(),
  Special: __t.unit(),
  Speed: __t.unit(),
});
export type Stat = __Infer<typeof Stat>;

export const StatBlock = __t.object("StatBlock", {
  hp: __t.u16(),
  attack: __t.u16(),
  defense: __t.u16(),
  special: __t.u16(),
  speed: __t.u16(),
});
export type StatBlock = __Infer<typeof StatBlock>;

export const SwitchEvent = __t.object("SwitchEvent", {
  speciesId: __t.u32(),
});
export type SwitchEvent = __Infer<typeof SwitchEvent>;

// The tagged union or sum type for the algebraic type `Temperament`.
export const Temperament = __t.enum("Temperament", {
  Hardy: __t.unit(),
  Brave: __t.unit(),
  Nimble: __t.unit(),
  Stalwart: __t.unit(),
  Mystic: __t.unit(),
  Fierce: __t.unit(),
  Cautious: __t.unit(),
  Quick: __t.unit(),
  Focused: __t.unit(),
});
export type Temperament = __Infer<typeof Temperament>;

export const TradeOffer = __t.object("TradeOffer", {
  id: __t.u64(),
  fromIdentity: __t.identity(),
  toIdentity: __t.identity(),
  get fromCard() {
    return MonsterCard;
  },
  get toCard() {
    return __t.option(MonsterCard);
  },
  get status() {
    return TradeStatus;
  },
  createdAtMs: __t.i64(),
});
export type TradeOffer = __Infer<typeof TradeOffer>;

// The tagged union or sum type for the algebraic type `TradeStatus`.
export const TradeStatus = __t.enum("TradeStatus", {
  AwaitingRecipient: __t.unit(),
  AwaitingInitiator: __t.unit(),
});
export type TradeStatus = __Infer<typeof TradeStatus>;

export const Training = __t.object("Training", {
  hp: __t.u16(),
  attack: __t.u16(),
  defense: __t.u16(),
  special: __t.u16(),
  speed: __t.u16(),
});
export type Training = __Infer<typeof Training>;

export const TypeRelationRow = __t.object("TypeRelationRow", {
  id: __t.u64(),
  get attack() {
    return Affinity;
  },
  get defend() {
    return Affinity;
  },
  get effect() {
    return Effectiveness;
  },
});
export type TypeRelationRow = __Infer<typeof TypeRelationRow>;

