// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

// The tagged union or sum type for the algebraic type `ActionState`.
export const ActionState = __t.enum("ActionState", {
  Idle: __t.unit(),
  Walking: __t.unit(),
  Jumping: __t.unit(),
});
export type ActionState = __Infer<typeof ActionState>;

export const Character = __t.object("Character", {
  entityId: __t.u64(),
  mapId: __t.u32(),
  tileX: __t.i32(),
  tileY: __t.i32(),
  get facing() {
    return Direction;
  },
  get action() {
    return ActionState;
  },
  moveStartedAtMs: __t.i64(),
  spriteId: __t.u32(),
  get moveQueue() {
    return __t.array(MoveInput);
  },
});
export type Character = __Infer<typeof Character>;

export const Config = __t.object("Config", {
  id: __t.u32(),
  mapId: __t.u32(),
});
export type Config = __Infer<typeof Config>;

// The tagged union or sum type for the algebraic type `Direction`.
export const Direction = __t.enum("Direction", {
  North: __t.unit(),
  South: __t.unit(),
  East: __t.unit(),
  West: __t.unit(),
});
export type Direction = __Infer<typeof Direction>;

// The tagged union or sum type for the algebraic type `MoveInput`.
export const MoveInput = __t.enum("MoveInput", {
  get Step() {
    return Direction;
  },
  Jump: __t.unit(),
});
export type MoveInput = __Infer<typeof MoveInput>;

export const MovementTickSchedule = __t.object("MovementTickSchedule", {
  id: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type MovementTickSchedule = __Infer<typeof MovementTickSchedule>;

export const Npc = __t.object("Npc", {
  entityId: __t.u64(),
  homeX: __t.i32(),
  homeY: __t.i32(),
  wanderRadius: __t.i32(),
  nextMoveAtMs: __t.i64(),
});
export type Npc = __Infer<typeof Npc>;

export const Player = __t.object("Player", {
  identity: __t.identity(),
  entityId: __t.u64(),
  name: __t.string(),
  online: __t.bool(),
  lastInputSeq: __t.u64(),
});
export type Player = __Infer<typeof Player>;

