// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import EnqueueMoveReducer from "../enqueue_move_reducer";
import JoinGameReducer from "../join_game_reducer";

export type EnqueueMoveParams = __Infer<typeof EnqueueMoveReducer>;
export type JoinGameParams = __Infer<typeof JoinGameReducer>;

